apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: data-cleanup
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 10
      containers:
      - image: gcr.io/PROJECT_ID/data-cleanup:latest
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
```